version: '3'
services:
  backend:
    build: ./backend
    ports:
     - "8090:8090"
  db:
    build: ./database
    ports:
    - "5432:5432"
  frontend:
    build: ./frontend
    ports:
    - "3000:3000"
