version: '3'
services:
  backend:
    container_name: skrp_backend
    build: ./backend
    ports:
      - "8090:8090"
    environment:
      - PGHOST=db
    links:
      - db
      - mocker
    networks:
      - backend
  db:
    container_name: skrp_db
    build: ./database
    ports:
    - "5432:5432"
    networks:
      - backend
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5
  frontend:
    container_name: skrp_frontend
    build: ./frontend
    ports:
    - "3000:3000"
    environment:
      - DATA_SOURCE=mocker:3001
    links:
      - backend
      - mocker
    networks:
      - backend
  mocker:
    container_name: skrp_mocker
    build: ./mocker
    ports:
    - "3001:3001"
    networks:
      - backend
  client:
    container_name: skrp_client
    build: ./client
    networks:
      - backend
    environment:
      - BACKEND_HOST=backend:8090
      - NETJSON_HOST=mocker:3001
      - INTERVAL=30.0
    depends_on:
      - db
      - backend
      - mocker


networks:
  backend:
    driver: "bridge"
